apiVersion: v1
kind: Secret
metadata:
  name: pokekube-db-secret
type: Opaque
data:
  POSTGRES_USER: cG9rZW1vbg==
  POSTGRES_PASSWORD: cG9rZW1vbl9wYXNzd29yZA==
  POSTGRES_DB: cG9rZW1vbl9mYXZvcml0ZXM=

